{{ if .Values.adminer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  selector:
    app: adminer
  ports:
  - name: "8080"
    port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer:4.3.1-standalone
        name: adminer
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 5m
{{ end }}