apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  selector:
    app: solr
  ports:
  - name: "8983"
    port: 8983
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - image: orihoch/data4dappl-solr
        name: solr
        ports:
        - containerPort: 8983
        resources:
          requests:
            cpu: 20m
